### PR TITLE
Feature: Add support for timedelta and relativedelta return value.

### LINKED ISSUE #4: Add direct to timedelta conversion
Right now, if you enter `1 month`, then convert it into a timedelta as such:
```python
datetime.timedelta(seconds=parse('1 month'))
```

Then, if you add that timedelta to a datetime, the value will be incorrect in certain months, as per the readme:
> For months and years, the library does not consider complications such as leap- years and leap-seconds. Instead, it assumes "30 days for a month" and "365 days for a year" as the basis for calculations with those units.

It would be helpful to have a convert to timedelta option to handle stuff like this.

### PR DESCRIPTION
**Pull request by onegreyonewhite**
#### Changelog
* Feature: Make all calculations in ``datetime.timedelta`` or ``dateutil.relativedelta.relativedelta``.
* Feature: Provide to return timedelta value.

Closes #4

### CODE REVIEW

**Comment by onegreyonewhite** [comment]
@2br-2b you can check this variant. What do you think?

**Comment by onegreyonewhite** [comment]
```bash
python -m timeit -s 'from pytimeparse2 import parse' 'parse("26h")'
```

* old - `100000 loops, best of 5: 3.34 usec per loop`
* new - `100000 loops, best of 5: 6.48 usec per loop`

**Comment by 2br-2b** [comment]
I've just had a chance to briefly review the code, haven't tested it out yet. I'll write some unit tests later (probably copy the current ones)

Might it be better to have separate functions for `parse_to_int`, `parse_to_timedelta`? For compatibility's sake, you could make `parse` and `parse_to_timedelta`.

I do like what you did when checking for `relative_timedelta`, but I would think that for a library, it's better to force people to be explicit about whether they're using dateutil or not. I don't know what the best way to do this would be (without creating a separate importable class or a separate package for using dateutil), but I just got a feeling.

I'll try to have some unit tests up and running... soon... after finals are done.

But thanks for adding this so quickly!

**Comment by 2br-2b** [comment]
I wrote the unit tests in #7, and it seems that it works except where decimals are involved. For example (in my branch):
```
FAIL: test_timeparse_31 (tests.TestRelativeDeltaOutput)
timeparse test case 31.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 740, in test_timeparse_31
    self.assertEqual(timeparse.parse('5.6 wk', as_timedelta=True), relativedelta(seconds = 3386880))
AssertionError: relativedelta(days=+39) != relativedelta(days=+39, hours=+4, minutes=+48)

======================================================================
FAIL: test_timeparse_9 (tests.TestRelativeDeltaOutput)
timeparse test case 9.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 531, in test_timeparse_9
    self.assertEqual(timeparse.parse('4:13:02.266', as_timedelta=True), relativedelta(seconds = 15182, microseconds=266 * 1000))
AssertionError: relativedelta(hours=+4, minutes=+13, seconds=+2) != relativedelta(hours=+4, minutes=+13, seconds=+2, microseconds=+266000)
```

<details>
<summary>All in all, I end up with 21 failed cases with either this or what appears to be similar issues:</summary>

```
> python .\tests.py
........................................................F.F.F.F....FFFFFFFF.FF.....F....FFF.....F...F...F
======================================================================
FAIL: test_combined (tests.TestRelativeDeltaOutput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 769, in test_combined
    self.assertEqual(timeparse.parse('1y2mo3w4d5h6m7s8ms', as_timedelta=True), relativedelta(seconds = 38898367, microseconds=8000))
AssertionError: relativedelta(years=+1, months=+2, days=+25, hours=+5, [38 chars]8000) != relativedelta(days=+450, hours=+5, minutes=+6, seconds=[18 chars]8000)

======================================================================
FAIL: test_plain_numbers (tests.TestRelativeDeltaOutput)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 764, in test_plain_numbers
    self.assertEqual(timeparse.parse('10.1', as_timedelta=True), relativedelta(seconds = 10, microsecond = 100000))
AssertionError: relativedelta(seconds=+10) != relativedelta(seconds=+10, microsecond=100000)

======================================================================
FAIL: test_timeparse_10 (tests.TestRelativeDeltaOutput)
timeparse test case 10.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 537, in test_timeparse_10
    self.assertEqual(timeparse.parse('2:04:13:02.266', as_timedelta=True),
AssertionError: relativedelta(days=+2, hours=+4, minutes=+13, seconds=+2) != relativedelta(days=+2, hours=+4, minutes=+13, seconds=+2, microsecond=266000)

======================================================================
FAIL: test_timeparse_12 (tests.TestRelativeDeltaOutput)
timeparse test case 12.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 584, in test_timeparse_12
    self.assertEqual(timeparse.parse('2 days,  4:13:02.266', as_timedelta=True),
AssertionError: relativedelta(days=+2, hours=+4, minutes=+13, seconds=+2) != relativedelta(days=+2, hours=+4, minutes=+13, seconds=+2, microsecond=266000)

======================================================================
FAIL: test_timeparse_16b (tests.TestRelativeDeltaOutput)
timeparse test case 16b.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 626, in test_timeparse_16b
    self.assertEqual(timeparse.parse('1.75 s', as_timedelta=True), relativedelta(seconds = 1, microsecond = 10000 * 75))
AssertionError: relativedelta(seconds=+1) != relativedelta(seconds=+1, microsecond=750000)

======================================================================
FAIL: test_timeparse_16c (tests.TestRelativeDeltaOutput)
timeparse test case 16c.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 632, in test_timeparse_16c
    self.assertEqual(timeparse.parse('1.75 sec', as_timedelta=True), relativedelta(seconds = 1, microsecond = 10000 * 75))
AssertionError: relativedelta(seconds=+1) != relativedelta(seconds=+1, microsecond=750000)

======================================================================
FAIL: test_timeparse_16d (tests.TestRelativeDeltaOutput)
timeparse test case 16d.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 638, in test_timeparse_16d
    self.assertEqual(timeparse.parse('1.75 secs', as_timedelta=True), relativedelta(seconds = 1, microsecond = 75 * 10000))
AssertionError: relativedelta(seconds=+1) != relativedelta(seconds=+1, microsecond=750000)

======================================================================
FAIL: test_timeparse_16e (tests.TestRelativeDeltaOutput)
timeparse test case 16e.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 644, in test_timeparse_16e
    self.assertEqual(timeparse.parse('1.75 second', as_timedelta=True), relativedelta(seconds = 1, microsecond = 75 * 10000))
AssertionError: relativedelta(seconds=+1) != relativedelta(seconds=+1, microsecond=750000)

======================================================================
FAIL: test_timeparse_16f (tests.TestRelativeDeltaOutput)
timeparse test case 16f.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 650, in test_timeparse_16f
    self.assertEqual(timeparse.parse('1.75 seconds', as_timedelta=True), relativedelta(seconds = 1, microsecond = 75 * 10000))
AssertionError: relativedelta(seconds=+1) != relativedelta(seconds=+1, microsecond=750000)

======================================================================
FAIL: test_timeparse_17 (tests.TestRelativeDeltaOutput)
timeparse test case 17.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 656, in test_timeparse_17
    self.assertEqual(timeparse.parse('1.2 m', as_timedelta=True), relativedelta(seconds = 72))
AssertionError: relativedelta(minutes=+1) != relativedelta(minutes=+1, seconds=+12)

======================================================================
FAIL: test_timeparse_18 (tests.TestRelativeDeltaOutput)
timeparse test case 18.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 662, in test_timeparse_18
    self.assertEqual(timeparse.parse('1.2 min', as_timedelta=True), relativedelta(seconds = 72))
AssertionError: relativedelta(minutes=+1) != relativedelta(minutes=+1, seconds=+12)

======================================================================
FAIL: test_timeparse_19 (tests.TestRelativeDeltaOutput)
timeparse test case 19.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 668, in test_timeparse_19
    self.assertEqual(timeparse.parse('1.2 mins', as_timedelta=True), relativedelta(seconds = 72))
AssertionError: relativedelta(minutes=+1) != relativedelta(minutes=+1, seconds=+12)

======================================================================
FAIL: test_timeparse_20 (tests.TestRelativeDeltaOutput)
timeparse test case 20.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 674, in test_timeparse_20
    self.assertEqual(timeparse.parse('1.2 minute', as_timedelta=True), relativedelta(seconds = 72))
AssertionError: relativedelta(minutes=+1) != relativedelta(minutes=+1, seconds=+12)

======================================================================
FAIL: test_timeparse_21 (tests.TestRelativeDeltaOutput)
timeparse test case 21.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 680, in test_timeparse_21
    self.assertEqual(timeparse.parse('1.2 minutes', as_timedelta=True), relativedelta(seconds = 72))
AssertionError: relativedelta(minutes=+1) != relativedelta(minutes=+1, seconds=+12)

======================================================================
FAIL: test_timeparse_27 (tests.TestRelativeDeltaOutput)
timeparse test case 27.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 716, in test_timeparse_27
    self.assertEqual(timeparse.parse('1.24 days', as_timedelta=True), relativedelta(seconds = 107136))
AssertionError: relativedelta(days=+1) != relativedelta(days=+1, hours=+5, minutes=+45, seconds=+36)

======================================================================
FAIL: test_timeparse_31 (tests.TestRelativeDeltaOutput)
timeparse test case 31.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 740, in test_timeparse_31
    self.assertEqual(timeparse.parse('5.6 wk', as_timedelta=True), relativedelta(seconds = 3386880))
AssertionError: relativedelta(days=+39) != relativedelta(days=+39, hours=+4, minutes=+48)

======================================================================
FAIL: test_timeparse_32 (tests.TestRelativeDeltaOutput)
timeparse test case 32.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 746, in test_timeparse_32
    self.assertEqual(timeparse.parse('5.6 week', as_timedelta=True), relativedelta(seconds = 3386880))
AssertionError: relativedelta(days=+39) != relativedelta(days=+39, hours=+4, minutes=+48)

======================================================================
FAIL: test_timeparse_33 (tests.TestRelativeDeltaOutput)
timeparse test case 33.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 752, in test_timeparse_33
    self.assertEqual(timeparse.parse('5.6 weeks', as_timedelta=True), relativedelta(seconds = 3386880))
AssertionError: relativedelta(days=+39) != relativedelta(days=+39, hours=+4, minutes=+48)

======================================================================
FAIL: test_timeparse_9 (tests.TestRelativeDeltaOutput)
timeparse test case 9.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 531, in test_timeparse_9
    self.assertEqual(timeparse.parse('4:13:02.266', as_timedelta=True), relativedelta(seconds = 15182, microseconds=266 * 1000))
AssertionError: relativedelta(hours=+4, minutes=+13, seconds=+2) != relativedelta(hours=+4, minutes=+13, seconds=+2, microseconds=+266000)

======================================================================
FAIL: test_timeparse_granularity_3 (tests.TestRelativeDeltaOutput)
Check that minute-level granularity does not apply inappropriately.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 558, in test_timeparse_granularity_3
    self.assertEqual(timeparse.parse('7:02.223', granularity='minutes', as_timedelta=True), relativedelta(seconds = 2, microsecond = 1000 * 223, minute=7))
AssertionError: relativedelta(minutes=+7, seconds=+2) != relativedelta(seconds=+2, minute=7, microsecond=223000)

======================================================================
FAIL: test_timeparse_unparsed (tests.TestRelativeDeltaOutput)
Check that unparsed values tries to converts into int().
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\abold\Desktop\pytimeparse2\tests.py", line 571, in test_timeparse_unparsed
    self.assertEqual(timeparse.parse(-18.333, as_timedelta=True), relativedelta(seconds = -18, microsecond = -333 * 1000))
AssertionError: relativedelta(seconds=-18) != relativedelta(seconds=-18, microsecond=-333000)

----------------------------------------------------------------------
Ran 105 tests in 0.043s

FAILED (failures=21)
```
</details>

It seems that somehow, the decimals are throwing the code for a loop. I may look into that a bit more after finals... (though that's what I said about writing this... 😔)

**Pull request merged**
